USE master;
GO
CREATE LOGIN dbm_login WITH PASSWORD = 'Black123!@#'; --密码和SA密码保持一致
CREATE USER dbm_user FOR LOGIN dbm_login;
GRANT VIEW SERVER STATE To dbm_login;
GRANT CREATE AVAILABILITY GROUP To dbm_login;
GRANT ALTER ANY AVAILABILITY GROUP To dbm_login;
GRANT CREATE ENDPOINT TO dbm_login;
GRANT ALTER ANY ENDPOINT TO dbm_login;
GO
--创建主密钥
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'Black123!@#';
--创建证书 这里有两个"CERT1",建议每台机器都改成不同的名称以作区分
CREATE CERTIFICATE CERT2 WITH SUBJECT = 'CERT1', START_DATE = '2017-01-01',EXPIRY_DATE = '2099-12-30';
--把刚才创建的证书备份到文件 这里也有两个CERT1要改
BACKUP CERTIFICATE CERT2 TO FILE = '/var/opt/mssql/CERT2.cer';
GO
