version: '3'

services:
  db1:
    container_name: sqlNode1
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlNode1
    domainname: lab.local
    volumes:  #注意下面的路径映射，冒号左侧为本机地址，右侧为容器地址，左侧路径必须有777权限，否则会启动失败
      - D:\dbs\1:/var/opt/mssql #MSSQL的MDB文件存放地址
    privileged: true
    environment:
      SA_PASSWORD: "Black123!@#" #数据库SA用户的密码
      TZ: "Asia/Shanghai" #设置时区
      ACCEPT_EULA: "Y"
    ports:
      - "1501:1433" #主机和容器的端口映射
    extra_hosts: #写入/etc/hosts
      sqlNode2.lab.local: "172.16.0.3" #节点2的IP
      sqlNode3.lab.local: "172.16.0.4" #节点3的IP
    networks:
      internal:
        ipv4_address: 172.16.0.2 #本机IP

  db2:
    container_name: sqlNode2
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlNode2
    domainname: lab.local
    volumes:
      - D:\dbs\2:/var/opt/mssql
#      - /etc/localtime:/etc/localtime:ro
    privileged: true
    environment:
      SA_PASSWORD: "Black123!@#"
      TZ: "Asia/Shanghai"
      ACCEPT_EULA: "Y"
    ports:
      - "1502:1433"
    extra_hosts:
      sqlNode1.lab.local: "172.16.0.2"
      sqlNode3.lab.local: "172.16.0.4"
    networks:
      internal:
        ipv4_address: 172.16.0.3

  db3:
    container_name: sqlNode3
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlNode3
    domainname: lab.local
    volumes:
      - D:\dbs\3:/var/opt/mssql
    #      - /etc/localtime:/etc/localtime:ro
    privileged: true
    environment:
      SA_PASSWORD: "Black123!@#"
      TZ: "Asia/Shanghai"
      ACCEPT_EULA: "Y"
    ports:
      - "1503:1433"
    extra_hosts:
      sqlNode1.lab.local: "172.16.0.2"
      sqlNode2.lab.local: "172.16.0.3"
    networks:
      internal:
        ipv4_address: 172.16.0.4

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
