version: "1.0"
services:
  jenkins:
    image: shoppo0505/jenkins_java17:1.0.0
    container_name: jenkins
    user : "1000"
    ports:
      - 9999:8080
      - 5000:50000
    volumes:
      - D:\Git\Docker\Dockerfiles\src\docker_jenkins\jenkins_home\:/var/jenkins_home/

  jenkins2:
    image: jenkins/jenkins:lts
    container_name: jenkinslts
    ports:
      - 9998:8080
      - 5001:50000
