version: '3.7'
services:
  harbor:
    image: goharbor/harbor-offline-installer:v2.2.2
    expose:
      - 80
      - 443
    volumes:
      - ./data:/data
      - ./certs:/certs
    restart: always
    hostname: harbor.domain.com
    environment:
      - TZ=Asia/Shanghai
      - HARBOR_ADMIN_PASSWORD=password
